name: cs109project
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - click=8.1.8
  - comm=0.2.2
  - debugpy=1.8.7
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.13.5
  - python-dotenv=1.1.0
  - python_abi=3.13
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - eval-type-backport==0.2.2
      - fonttools==4.59.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.176.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mistralai==1.9.2
      - narwhals==2.0.1
      - numpy==2.3.1
      - pandas==2.3.1
      - pillow==11.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.4
      - rpds-py==0.26.0
      - rsa==4.9.1
      - scipy==1.16.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==1.47.1
      - tenacity==9.1.2
      - toml==0.10.2
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - watchdog==6.0.0
